### ISSUE TITLE
Опечатка 

### ISSUE THREAD

**Issue by 0snilcy** [htmlacademy-nodejs/code-and-magick#11]
https://github.com/htmlacademy-nodejs/code-and-magick/blob/6a50a3a846bfda5874b0a73225acf870074e7f20/test/get-wizard.test.js#L67
Опечатка _xit_.

**Comment by zeckson** [comment]
Это не опечатка, это выключенный временно тест. Для того чтобы выключить тест можно использовать функцию `xit` или чтобы выключить группу тестов `xdescribe`

**Comment by zeckson** [comment]
https://stackoverflow.com/questions/32723167/how-to-programmatically-skip-a-test-in-mocha#32724129

**Comment by vldmkrsh** [comment]
Я настаиваю на опечатке — Шапокляк натравит на тебя Ларису за то, что её назвали «Шаполкляк»!

**Comment by zeckson** [comment]
> Я настаиваю на опечатке — Шапокляк натравит на тебя Ларису за то, что её назвали «Шаполкляк»!

Ахахахахаха! =)

**Comment by kicumkicum** [comment]
- [x] вернул xit
- [x] поправил Шапокляк
